<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Routing\formStateInterface;
use Drupal\Core\Routing\EntityInterface;
use Drupal\node\NodeInterface;

/**Implement hook hello_cron*/
function hello_cron() {
  drupal_set_message(t('Hello module cron task done.'),'warning');
}

/**Implement hook hello_help*/
function hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block module.
    case 'help.page.hello':
      return '<p>' . t('I\'m  hello help.')
     . '</p>';
  }
}

/** Implement hook hello_user_login*/
function hello_user_login($account) {
	drupal_set_message(t('welcome dear %name',
['%name' => $account->getAccountName()]
));
}

/** Implement hello_node_update().
 * @param \Drupal\node\NodeInterface $node
 */
function hello_node_update(NodeInterface $node) {
	$user = \Drupal::currentUser();
	$database = \Drupal::database();
	$database->insert('hello_node_history')
	  ->fields([
        'nid'=> $node->id(),
        'titlenid'=> $node->label(),
        'uid'=> $user->id(),
        'update_time'=> $node->getChangedTime(),
	  ])
	  ->execute();
}

/** Implement hello_node_delete().
 * @param \Drupal\node\NodeInterface $node
 */
function hello_node_delete(NodeInterface $node) {
	$database = \Drupal::database();
	$database->delete('hello_node_history')
	  ->condition('nid',$node->id())
	  ->execute();
}

